### ISSUE TITLE
Replace default windows explorer "delete" with byenew  

### ISSUE THREAD

**Issue by rizrmd** [apankrat/byenow#1]
Byenow is awesome!

Now, How do I replace default windows explorer 'delete' using byenow. This means:
   - Right click, delete, and then confirms it.
   - Pressing delete on keyboard, and then confirms it.

would execute byenow instead of the slow windows delete.

**Comment by apankrat** [comment]
Glad you like it, but no idea how to do what you want. I'm pretty sure it's perfectly doable though.
