### ISSUE TITLE
Command exit codes

### ISSUE THREAD

**Issue by highend** [apankrat/byenow#2]
Hi,

great tool! Deletes a Visual Studio Code folder (755 MB, 17.774 files, 2923 folders) from a ram disk in ~0.5 seconds (using --delete-ntapi)^^

One thing I'd like to request though: Could you implement different exit codes?
Atm `@echo %errorlevel%` after executing byenow.exe will always report 0 even if byenow found an 
 error during delete.

So one way would be:
Return 0 if no errors were found
and 1... x for the number of errors found

This would be really helpful...

**Comment by apankrat** [comment]
It's a valid request, I'll fix this. It's not possible to return the error count though... but perhaps returning a log(n) could work. Let me see what I can do.

**Comment by apankrat** [comment]
Done with 6e39e0ea7b5f4bb, in version 0.3, available from https://iobureau.com/byenow/
