### ISSUE TITLE
Deletion confirmation under Windows doesn't work

### ISSUE THREAD

**Issue by graphixillusion** [apankrat/byenow#4]
Hi there. As the title says, when you try to delete something with the command

`byenow "foldername"`

the confirmation's prompt appears: at this point if you type **"yes"** nothing happens. The command will processes the deletion only if you use the **"--yes"** tag.

**Comment by apankrat** [comment]
Whoops, fixed in [0.4](https://iobureau.com/byenow/byenow-0.4.zip) with 9786065cd29f254e0432cba7dca0c8b30e4d3faf. Thanks for the report.
