### ISSUE TITLE
Releases on Github

### ISSUE THREAD

**Issue by Luckz** [apankrat/byenow#5]
If you also had the downloads as Github releases, it would be easier to auto-update this in some way or another.

**Comment by apankrat** [comment]
Releases I will look into, but I'm certainly not interested in distributing this through Github.

**Comment by Luckz** [comment]
You mean you want to keep downloads through your domain?
(It's likely more difficult to automagically get the current version string and appropriate download URL that way)

**Comment by apankrat** [comment]
I mean that for this project I'm not interested in using GH for anything except making sources easy to browse.

**Comment by sergeevabc** [comment]
[0.11](https://github.com/apankrat/byenow/releases/download/byenow-0.11.0.0/byenow-0.11.zip) release (either x86 or x64) outputs version 0.10 as follows
```
Faster folder deleter, ver 0.10, freeware, https://iobureau.com/byenow
Syntax: byenow.exe [options] <folder>
...
```

**Comment by apankrat** [comment]
@sergeevabc - thanks, should be fixed now. Updated the package on the website as well.
