### ISSUE TITLE
Access with context menu

### ISSUE THREAD

**Issue by ibay770** [apankrat/byenow#7]
Is there a way that you can right click on the folder you want to delete, right click, Delete with byenow, and bynow does everything in the background? Thanks in advance.

**Comment by apankrat** [comment]
Yes, there is a way. Lookup "Windows Explorer right-click menu extensions".

**Comment by ibay770** [comment]
Thank you, yes I tried that, but I don't know what commands to use to launch it on any folder. I put it in the windows folder, and added the--threads 13 --yes --yolo  arguments but nothing happens when I run it on a folder in documents for example.

**Comment by sergeevabc** [comment]
@ibay770, try the following steps:
* put _byenow.exe_ somewhere in your PATH (e.g. C:\Windows)
* open folder _%APPDATA%\Microsoft\Windows\SendTo_
* create DeleteFolder.cmd with ```@byenow.exe -x "%~1"``` inside

![image](https://user-images.githubusercontent.com/373718/201478881-0aa1c11c-79d8-4b8f-8cf7-fd808bcdc72c.png)

**Comment by rampageX** [comment]
install.bat: (side by byenow.exe, Run as Administrator)
```
reg add "HKCR\Directory\shell\Fast Delete" /ve /d "Fast Delete" /f
reg add "HKCR\Directory\shell\Fast Delete" /v Icon /d "%~dp0byenow.ico" /f
reg add "HKCR\Directory\shell\Fast Delete\command" /ve /d "%~dp0byenow.exe \"%%1\" -s" /f
```
uninstall.bat:
`reg delete "HKCR\Directory\shell\Fast Delete" /f`

Result:

![2022-11-13_022243](https://user-images.githubusercontent.com/994081/201489197-74fa5c20-f604-467e-b0e4-5b236a9b8a9e.png)

0.7 bat include:


[byenow-0.7.zip](https://github.com/apankrat/byenow/files/9995645/byenow-0.7.zip)

**Comment by apankrat** [comment]
I added `-o` or `--omni-delete` option in 0.8 to allow passing a _file_ path, in which case it will try and delete just that file. It will also observe `--preview` and `--delete-ntapi`.

**Comment by sergeevabc** [comment]
@apankrat, thanks. However ```-o``` usually stands for _output filename_, and that omni long prefix we will forget in a week because the word itself is, well, rare among command line utils (I have a great deal of them since 90s). I would make it ```-f```, because it is related to files, but you're the boss here.
