### ISSUE TITLE
Way to delete a specific file

### ISSUE THREAD

**Issue by sergeevabc** [apankrat/byenow#8]
Dear @apankrat, why the scope is limited to folders only, why no ability to delete a file?

```console
$ byenow ghostwriter_win64.zip
Error: specified path points at a file - [X:\ghostwriter_win64.zip]
```

**Comment by apankrat** [comment]
Because it's a folder removal utility rather than an universal deletion tool.

I have no plans to change this, so I'll close this issue.

**Comment by apankrat** [comment]
> I have no plans to change this

Added in 0.8 after seeing [this comment](https://github.com/apankrat/byenow/issues/7#issuecomment-1312545147) by @rampageX.
