### ISSUE TITLE
Cyrillic paths

### ISSUE THREAD

**Issue by sergeevabc** [apankrat/byenow#9]
Dear @apankrat, byenow 0.6 does not output Cyrillic paths on my on Windows 7 x64.

It looks this way

```console
C:\>byenow Мяу
Remove [C:\
```

Then I press 'n', of course, and it becomes

```console
C:\>byenow Мяу
Remove [C:\n
```

**Comment by apankrat** [comment]
Yep, thanks, fixed with 0e72fe1ca3bd8c4c36d53a4f4d0f730600150b99.

Binary package - https://iobureau.com/byenow/byenow-0.7.zip.
